# Site settings
title: Alexia Weiller's page
email: alexia.weiller@gmail.com
description: "Keep moving forward"
baseurl: ""
url: "http://AlexiaWeiller.github.io"
linkedin_username: Alexia (Matouskoff) Weiller  
github_username:  Alexiaweiller

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
